tls:
  options:
    default:
      minVersion: VersionTLS10
      cipherSuites:
        - TLS_RSA_WITH_AES_128_CBC_SHA
        - TLS_RSA_WITH_AES_256_CBC_SHA
        - TLS_RSA_WITH_3DES_EDE_CBC_SHA
  certificates:
    - certFile: /data/passport-mock.crt
      keyFile: /data/passport-mock.key
  stores:
    default:
      defaultCertificate:
        certFile: /data/passport-mock.crt
        keyFile: /data/passport-mock.key
